### ISSUE TITLE
setChannel does not work reliably.

### ISSUE THREAD

**Issue by cfnz** [RobTillaart/HC4051#4]
Took me a while to find as I started debugging my hardware, then my software, then libraries...

Doing digitalReads after setting the channel did not report what I expected.

I am not that used to bit-wise logic, so that didn't help... but I believe there is an error in setChannel. I have fixed the code, and it seems to work... I am not too created many PR in GitHub, but will give it a go.

In case the pull request doesn't work, the problem is that the pins array index only decrements if there is a change on that pin, whereas it should decrement regardless.

**Comment by RobTillaart** [comment]
Thanks for reporting
As I am rather busy this month it will take a while to dive into your issue.
Labelled as bug to give it prio
